server:
  port: 8080 # 项目启动端口号
  servlet:
    context-path: /api  # 项目接口
spring:
  application: # 项目名称
    name: picture
  datasource: # 数据库连接配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picture
    username: root
    password: 123456